version: '3.1'
services:
  sprinbboot_ws:
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - mongo_db
    links:
      - mongo_db
    restart: always
    #args:
    #  - ENV_USERS=Test
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo_db/users
      ENV_USERS: Test
  mongo_db:
    image: "mongo"
    container_name: mongo_db
    restart: always
#    volumes:
#      - ./data:/data/db
    ports:
      - "27017:27017"